# Generated by Django 3.1.7 on 2021-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'student_leaderboard',
            },
        ),
    ]
